### ISSUE TITLE
need coffee support

### ISSUE THREAD

**Issue by ginus** [HiDeoo/autocomplete-lodash#3]
please add coffee support。

**Comment by HiDeoo** [comment]
Hi, thanks for your feedback.

I'm totally ok with adding support for CoffeeScript to the package although I'm not gonna do that myself.

I'm not a CoffeeScript developer / user and I'm a bit short on time currently so I don't have the time to learn multiple things:

- Can Lodash be used out of the box in CoffeeScript, are all methods identical, are all methods available, etc.?
- Are all the functions signatures the same? Is `_.function` still used? Would it be `_function`? Is there any advantages, etc.?
- Should I call function with parenthesis? Without? Is there any advantages, etc.?

The last thing I want would be to provide *bad* support for a new language.

Having said that, I would be happy to review and consider any pull request.

**Comment by ginus** [comment]
ok，just wait my pr
